# Generated by Django 5.0.2 on 2024-04-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cartitem'),
        ('Products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='Cart.CartItem', to='Products.product'),
        ),
    ]
