# Generated by Django 5.0.2 on 2024-04-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
