# Generated by Django 5.0.2 on 2024-04-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('other_names', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_phone', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField()),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
    ]
