# Generated by Django 5.0.4 on 2024-04-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('other_names', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=25)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Store_Staff', 'Store Staff')], max_length=20)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
