# Generated by Django 5.0.2 on 2024-04-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('other_names', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('mobile_phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('role', models.CharField(choices=[('CLERK', 'Clerk'), ('DELIVERY', 'Delivery'), ('ADMIN', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
